import jsPDF from "jspdf";
import type { ScanResults } from "@/types/scan";
import { formatDateBD } from "@/utils/dateFormat";

interface ReportMeta {
  auditId: string;
  scanDate: Date;
  ipAddress: string | null;
  wordCount: number;
  creditsUsed: number;
  documentName?: string;
  userEmail?: string;
}

/* ─── Colors ─── */
const NAVY = "#1B263B";
const TEAL = "#00B894";
const RED = "#E53935";
const AMBER = "#FF9800";
const GREY = "#6B7280";
const LIGHT = "#F3F4F6";
const WHITE = "#FFFFFF";
const TRACK = "#DEE2E6";

const W = 210;
const MARGIN = 18;
const CW = W - MARGIN * 2;

const DISCLAIMER =
  "Results are probabilistic estimates. Hybrid/Edited text or partial-context scans (e.g., scanning 200 words from a 5000-word file) will result in False Positives. Full context is mandatory for accuracy.";

/* ─── 3-Tier Logic ─── */
function getTheme(aiPct: number): { accent: string; verdict: string; riskLabel: string } {
  if (aiPct > 70) return { accent: RED, verdict: "HIGH RISK", riskLabel: "High Risk" };
  if (aiPct < 30) return { accent: TEAL, verdict: "VERIFIED HUMAN", riskLabel: "Low Risk" };
  return { accent: AMBER, verdict: "MODERATE RISK", riskLabel: "Moderate Risk" };
}

function getSentenceLabel(pct: number) {
  if (pct <= 30) return "Human";
  if (pct <= 60) return "Mixed";
  return "AI";
}

function getSentenceLabelColor(pct: number) {
  if (pct <= 30) return TEAL;
  if (pct <= 60) return AMBER;
  return RED;
}

/* ─── Circular Gauge ─── */
function drawGauge(doc: jsPDF, cx: number, cy: number, radius: number, pct: number, color: string, label: string) {
  const trackW = 4;
  // Track circle
  doc.setDrawColor(TRACK);
  doc.setLineWidth(trackW);
  doc.circle(cx, cy, radius, "S");

  // Filled arc — approximate with many small line segments
  if (pct > 0) {
    doc.setDrawColor(color);
    doc.setLineWidth(trackW);
    const startAngle = -Math.PI / 2;
    const endAngle = startAngle + (2 * Math.PI * Math.min(pct, 100)) / 100;
    const steps = Math.max(Math.round(pct * 0.6), 2);
    const step = (endAngle - startAngle) / steps;
    for (let i = 0; i < steps; i++) {
      const a1 = startAngle + step * i;
      const a2 = startAngle + step * (i + 1);
      const x1 = cx + radius * Math.cos(a1);
      const y1 = cy + radius * Math.sin(a1);
      const x2 = cx + radius * Math.cos(a2);
      const y2 = cy + radius * Math.sin(a2);
      doc.line(x1, y1, x2, y2);
    }
  }

  // Center text
  doc.setFontSize(20);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(color);
  doc.text(`${pct}%`, cx, cy + 2, { align: "center" });

  // Label below gauge
  doc.setFontSize(7);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(NAVY);
  doc.text(label.toUpperCase(), cx, cy + radius + 8, { align: "center" });
}

/* ─── Page chrome (header + footer on every page) ─── */
function drawPageChrome(doc: jsPDF, accent: string, meta: ReportMeta) {
  // Header bar
  doc.setFillColor(NAVY);
  doc.rect(0, 0, W, 10, "F");
  doc.setFillColor(accent);
  doc.rect(0, 10, W, 2, "F");
  doc.setFontSize(7);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(WHITE);
  doc.text("Generated by Theorex Consulting", MARGIN, 7);
  doc.setFont("helvetica", "normal");
  doc.text("WhatsApp: +8801819185751", W - MARGIN, 7, { align: "right" });
  // Header disclaimer
  doc.setFontSize(5);
  doc.setTextColor(GREY);
  doc.text("Results are probabilistic estimates. Always apply human judgement.", W / 2, 16, { align: "center" });

  // Footer
  const fy = 273;
  doc.setFillColor(accent);
  doc.rect(0, fy, W, 1, "F");

  // Audit trail
  doc.setFontSize(5);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(GREY);
  doc.text(`Ref: ${meta.auditId}  |  IP: ${meta.ipAddress || "N/A"}`, MARGIN, fy + 4);

  // Disclaimer
  doc.setFontSize(4.5);
  const lines = doc.splitTextToSize(DISCLAIMER, CW);
  doc.text(lines, W / 2, fy + 8, { align: "center" });

  // Bottom bar
  doc.setFillColor(NAVY);
  doc.rect(0, 293, W, 4, "F");
  doc.setFontSize(5);
  doc.setTextColor(WHITE);
  doc.text("Generated by Theorex Consulting — Promoting Transparency Over Mere Detection", W / 2, 296, { align: "center" });
}

function newPage(doc: jsPDF, accent: string, meta: ReportMeta): number {
  doc.addPage();
  drawPageChrome(doc, accent, meta);
  return 22;
}

function ensurePage(doc: jsPDF, y: number, needed: number, accent: string, meta: ReportMeta): number {
  if (y + needed > 266) return newPage(doc, accent, meta);
  return y;
}

/* ─── Document Identity Pill ─── */
function drawPill(doc: jsPDF, x: number, y: number, w: number, label: string, value: string) {
  doc.setFillColor(LIGHT);
  doc.roundedRect(x, y, w, 12, 2, 2, "F");
  doc.setDrawColor(TRACK);
  doc.roundedRect(x, y, w, 12, 2, 2, "S");
  doc.setFontSize(5);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(GREY);
  doc.text(label.toUpperCase(), x + w / 2, y + 4, { align: "center" });
  doc.setFontSize(7);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(NAVY);
  // Truncate value if too wide
  let displayVal = value;
  while (doc.getTextWidth(displayVal) > w - 4 && displayVal.length > 3) {
    displayVal = displayVal.slice(0, -4) + "…";
  }
  doc.text(displayVal, x + w / 2, y + 10, { align: "center" });
}

/* ─── Thick Bar ─── */
function drawThickBar(doc: jsPDF, x: number, y: number, w: number, pct: number, label: string, color: string) {
  doc.setFontSize(7);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(NAVY);
  doc.text(label, x, y);
  const by = y + 2;
  const h = 8;
  doc.setFillColor(LIGHT);
  doc.roundedRect(x, by, w, h, 2, 2, "F");
  const filled = Math.max(w * (pct / 100), 1);
  doc.setFillColor(color);
  doc.roundedRect(x, by, filled, h, 2, 2, "F");
  // Percentage inside bar
  doc.setFontSize(7);
  doc.setFont("helvetica", "bold");
  if (pct > 15) {
    doc.setTextColor(WHITE);
    doc.text(`${pct}%`, x + filled - 3, by + 5.5, { align: "right" });
  } else {
    doc.setTextColor(NAVY);
    doc.text(`${pct}%`, x + filled + 3, by + 5.5);
  }
}

/* ═══════════════════════════════════════ */
/*           MAIN EXPORT                  */
/* ═══════════════════════════════════════ */
export function generatePdfReport(results: ScanResults, meta: ReportMeta) {
  const doc = new jsPDF("p", "mm", "a4");

  const aiPct = results.ai ? Math.round(results.ai.score * 100) : 0;
  const humanPct = results.ai ? Math.round(results.ai.originalScore * 100) : 100;
  const plagPct = results.plagiarism ? Math.round(results.plagiarism.score) : 0;
  const { accent, verdict, riskLabel } = getTheme(aiPct);

  /* ── PAGE 1 ── */
  drawPageChrome(doc, accent, meta);
  let y = 22;

  // Hero banner
  doc.setFillColor(NAVY);
  doc.roundedRect(MARGIN, y, CW, 26, 3, 3, "F");
  doc.setFontSize(16);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(WHITE);
  doc.text("Content Quality Report", MARGIN + 8, y + 11);
  // Verdict badge
  const bw = doc.getTextWidth(verdict) + 12;
  doc.setFillColor(accent);
  doc.roundedRect(W - MARGIN - bw - 6, y + 4, bw, 12, 2, 2, "F");
  doc.setFontSize(8);
  doc.setTextColor(WHITE);
  doc.text(verdict, W - MARGIN - bw / 2 - 6, y + 12, { align: "center" });
  // User email
  if (meta.userEmail) {
    doc.setFontSize(6);
    doc.setFont("helvetica", "normal");
    doc.setTextColor("#B0BEC5");
    doc.text(`User: ${meta.userEmail}`, MARGIN + 8, y + 20);
  }
  y += 32;

  // Document Identity Pills
  const pillW = (CW - 9) / 4;
  drawPill(doc, MARGIN, y, pillW, "Document", meta.documentName || "Untitled");
  drawPill(doc, MARGIN + pillW + 3, y, pillW, "Scan Date", formatDateBD(meta.scanDate));
  drawPill(doc, MARGIN + (pillW + 3) * 2, y, pillW, "Word Count", meta.wordCount.toLocaleString());
  drawPill(doc, MARGIN + (pillW + 3) * 3, y, pillW, "Audit ID", meta.auditId.slice(0, 8).toUpperCase());
  y += 18;

  // Circular Gauges
  const gaugeR = 18;
  const gaugeCY = y + gaugeR + 2;
  const leftCX = MARGIN + CW / 4;
  const rightCX = MARGIN + (CW * 3) / 4;
  drawGauge(doc, leftCX, gaugeCY, gaugeR, humanPct, TEAL, "Human Originality");
  drawGauge(doc, rightCX, gaugeCY, gaugeR, aiPct, accent, "AI Detection");
  y = gaugeCY + gaugeR + 14;

  // Risk Assessment card
  const raW = CW / 2;
  const raX = MARGIN + (CW - raW) / 2;
  doc.setFillColor(accent);
  doc.roundedRect(raX, y, raW, 12, 2, 2, "F");
  doc.setFontSize(10);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(WHITE);
  doc.text(riskLabel.toUpperCase(), raX + raW / 2, y + 8, { align: "center" });
  y += 18;

  // Executive Summary
  y = ensurePage(doc, y, 28, accent, meta);
  doc.setFillColor(LIGHT);
  doc.roundedRect(MARGIN, y, CW, 24, 2, 2, "F");
  doc.setDrawColor(TRACK);
  doc.roundedRect(MARGIN, y, CW, 24, 2, 2, "S");
  doc.setFontSize(8);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(NAVY);
  doc.text("Executive Summary", MARGIN + 5, y + 6);
  doc.setFontSize(7);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(GREY);
  const sum = `This ${meta.wordCount.toLocaleString()}-word document has been classified as "${verdict}" with ${humanPct}% human originality and ${aiPct}% AI-generated content. Plagiarism similarity: ${plagPct}%.`;
  doc.text(doc.splitTextToSize(sum, CW - 10), MARGIN + 5, y + 12);
  y += 30;

  // Thick Bars
  y = ensurePage(doc, y, 55, accent, meta);
  doc.setFontSize(9);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(NAVY);
  doc.text("Quality Signals Breakdown", MARGIN, y);
  y += 6;
  drawThickBar(doc, MARGIN, y, CW - 10, aiPct, "AI Pattern Level", accent);
  y += 16;
  drawThickBar(doc, MARGIN, y, CW - 10, humanPct, "Human Originality", TEAL);
  y += 16;
  if (results.plagiarism) {
    drawThickBar(doc, MARGIN, y, CW - 10, plagPct, "Plagiarism Match", plagPct > 20 ? RED : NAVY);
    y += 16;
  }

  /* ── SENTENCE TABLE ── */
  if (results.ai?.blocks && results.ai.blocks.length > 0) {
    y = newPage(doc, accent, meta);
    doc.setFontSize(12);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(NAVY);
    doc.text("Sentence-by-Sentence AI Analysis", MARGIN, y);
    y += 8;

    const drawTableHeader = () => {
      doc.setFillColor(NAVY);
      doc.rect(MARGIN, y, CW, 8, "F");
      doc.setFontSize(6.5);
      doc.setFont("helvetica", "bold");
      doc.setTextColor(WHITE);
      doc.text("#", MARGIN + 3, y + 5.5);
      doc.text("Sentence Content", MARGIN + 12, y + 5.5);
      doc.text("Label", W - MARGIN - 32, y + 5.5);
      doc.text("Confidence", W - MARGIN - 16, y + 5.5);
      y += 8;
    };
    drawTableHeader();

    results.ai.blocks.forEach((block, i) => {
      const pct = Math.round(block.fake * 100);
      const label = getSentenceLabel(pct);
      const lc = getSentenceLabelColor(pct);
      const maxTW = CW - 55;
      const wrapped = doc.splitTextToSize(block.text, maxTW);
      const rh = Math.max(7, wrapped.length * 3.5 + 3);

      if (y + rh > 266) {
        y = newPage(doc, accent, meta);
        drawTableHeader();
      }

      doc.setFillColor(i % 2 === 0 ? WHITE : LIGHT);
      doc.rect(MARGIN, y, CW, rh, "F");
      doc.setFontSize(6);
      doc.setFont("helvetica", "normal");
      doc.setTextColor(GREY);
      doc.text(String(i + 1), MARGIN + 3, y + 4.5);
      doc.setTextColor(NAVY);
      doc.text(wrapped, MARGIN + 12, y + 4.5);
      // Badge
      doc.setFillColor(lc);
      doc.roundedRect(W - MARGIN - 34, y + 1.5, 14, 5, 1, 1, "F");
      doc.setFontSize(5);
      doc.setFont("helvetica", "bold");
      doc.setTextColor(WHITE);
      doc.text(label, W - MARGIN - 27, y + 5, { align: "center" });
      // Mini bar
      const bx = W - MARGIN - 18;
      doc.setFillColor(LIGHT);
      doc.roundedRect(bx, y + 2, 12, 3, 0.5, 0.5, "F");
      doc.setFillColor(lc);
      doc.roundedRect(bx, y + 2, Math.max(12 * (pct / 100), 0.5), 3, 0.5, 0.5, "F");
      doc.setFontSize(5);
      doc.setTextColor(NAVY);
      doc.text(`${pct}%`, bx + 6, y + 8, { align: "center" });

      y += rh;
    });
  }

  /* ── ENHANCED SEAL ── */
  y = ensurePage(doc, y, 80, accent, meta);
  y += 14;
  const cx = W / 2;
  const cy = y + 28;

  // Outer ring (thick accent)
  doc.setDrawColor(accent);
  doc.setLineWidth(3);
  doc.circle(cx, cy, 28, "S");

  // Decorative dots ring
  doc.setFillColor(accent);
  const dotR = 24;
  for (let a = 0; a < 360; a += 10) {
    const rad = (a * Math.PI) / 180;
    const dx = cx + dotR * Math.cos(rad);
    const dy = cy + dotR * Math.sin(rad);
    doc.circle(dx, dy, 0.4, "F");
  }

  // Navy ring
  doc.setDrawColor(NAVY);
  doc.setLineWidth(1.8);
  doc.circle(cx, cy, 20, "S");

  // Inner accent ring
  doc.setDrawColor(accent);
  doc.setLineWidth(0.7);
  doc.circle(cx, cy, 15, "S");

  // Seal text
  doc.setFontSize(9);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(accent);
  doc.text("THEOREX", cx, cy - 5, { align: "center" });
  doc.setFontSize(7);
  doc.setTextColor(NAVY);
  doc.text("CONSULTING", cx, cy, { align: "center" });
  doc.setFontSize(5.5);
  doc.setTextColor(accent);
  doc.text("CERTIFIED AUDIT", cx, cy + 5, { align: "center" });

  // Verdict stamp inside seal
  doc.setFontSize(4.5);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(accent);
  doc.text(verdict, cx, cy + 10, { align: "center" });

  // WhatsApp below seal
  y = cy + 34;
  doc.setFontSize(6);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(GREY);
  doc.text("WhatsApp: +8801819185751", cx, y, { align: "center" });

  y += 8;
  // Signature line
  doc.setDrawColor(NAVY);
  doc.setLineWidth(0.5);
  doc.line(cx - 35, y, cx + 35, y);
  y += 4;
  doc.setFontSize(6);
  doc.setTextColor(GREY);
  doc.text("Authorized Digital Signature — Theorex Consulting", cx, y, { align: "center" });

  // Save
  const ds = formatDateBD(meta.scanDate).replace(/\//g, "-");
  doc.save(`Theorex_Audit_Report_${ds}.pdf`);
}
