import jsPDF from "jspdf";
import type { ScanResults } from "@/types/scan";
import { formatDateBD } from "@/utils/dateFormat";

interface ReportMeta {
  auditId: string;
  scanDate: Date;
  ipAddress: string | null;
  wordCount: number;
  creditsUsed: number;
  documentName?: string;
  userEmail?: string;
}

const NAVY = "#1B263B";
const TEAL = "#00B894";
const RED = "#E53935";
const GREY = "#6B7280";
const LIGHT = "#F3F4F6";
const WHITE = "#FFFFFF";
const W = 210;
const MARGIN = 18;
const CW = W - MARGIN * 2;

const DISCLAIMER =
  "Results are probabilistic estimates. Hybrid/Edited text or partial-context scans (e.g., scanning 200 words from a 5000-word file) will result in False Positives. Full context is mandatory for accuracy.";

function getAccent(aiPct: number) { return aiPct > 70 ? RED : TEAL; }
function getVerdict(aiPct: number) { return aiPct > 70 ? "AI Written" : "Human Written"; }

function getRiskLabel(pct: number) {
  if (pct <= 14) return "Clean";
  if (pct <= 39) return "Low Risk";
  if (pct <= 59) return "Moderate";
  if (pct <= 84) return "High Risk";
  return "Critical";
}

function getSentenceLabel(pct: number) {
  if (pct <= 30) return "Human";
  if (pct <= 60) return "Mixed";
  return "AI";
}

function getSentenceLabelColor(pct: number) {
  if (pct <= 30) return TEAL;
  if (pct <= 60) return "#FF9800";
  return RED;
}

/* ─── Page chrome (header + footer on every page) ─── */
function drawPageChrome(doc: jsPDF, accent: string) {
  // Header bar
  doc.setFillColor(NAVY);
  doc.rect(0, 0, W, 10, "F");
  doc.setFillColor(accent);
  doc.rect(0, 10, W, 2, "F");
  doc.setFontSize(7);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(WHITE);
  doc.text("Generated by Theorex Consulting", MARGIN, 7);
  doc.setFont("helvetica", "normal");
  doc.text("WhatsApp: +8801819185751", W - MARGIN, 7, { align: "right" });
  // Header disclaimer
  doc.setFontSize(5);
  doc.setTextColor(GREY);
  doc.text("Results are probabilistic estimates. Always apply human judgement.", W / 2, 16, { align: "center" });

  // Footer disclaimer block
  const fy = 275;
  doc.setFillColor(accent);
  doc.rect(0, fy, W, 1, "F");
  doc.setFontSize(4.5);
  doc.setTextColor(GREY);
  doc.setFont("helvetica", "normal");
  const lines = doc.splitTextToSize(DISCLAIMER, CW);
  doc.text(lines, W / 2, fy + 3, { align: "center" });
  // Bottom bar
  doc.setFillColor(NAVY);
  doc.rect(0, 293, W, 4, "F");
  doc.setFontSize(5);
  doc.setTextColor(WHITE);
  doc.text("Generated by Theorex Consulting — Promoting Transparency Over Mere Detection", W / 2, 296, { align: "center" });
}

function newPage(doc: jsPDF, accent: string): number {
  doc.addPage();
  drawPageChrome(doc, accent);
  return 22;
}

function ensurePage(doc: jsPDF, y: number, needed: number, accent: string): number {
  if (y + needed > 268) return newPage(doc, accent);
  return y;
}

/* ─── Score Card ─── */
function drawCard(doc: jsPDF, x: number, y: number, w: number, h: number, value: string, label: string, color: string) {
  doc.setFillColor(LIGHT);
  doc.roundedRect(x, y, w, h, 2, 2, "F");
  doc.setDrawColor("#DEE2E6");
  doc.roundedRect(x, y, w, h, 2, 2, "S");
  doc.setFontSize(18);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(color);
  doc.text(value, x + w / 2, y + h / 2 - 1, { align: "center" });
  doc.setFontSize(6.5);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(GREY);
  doc.text(label.toUpperCase(), x + w / 2, y + h / 2 + 7, { align: "center" });
}

/* ─── Bar ─── */
function drawBar(doc: jsPDF, x: number, y: number, w: number, pct: number, label: string, color: string) {
  doc.setFontSize(7);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(NAVY);
  doc.text(label, x, y);
  const by = y + 2;
  doc.setFillColor(LIGHT);
  doc.roundedRect(x, by, w, 5, 1, 1, "F");
  doc.setFillColor(color);
  doc.roundedRect(x, by, Math.max(w * (pct / 100), 1), 5, 1, 1, "F");
  doc.setFontSize(7);
  doc.setTextColor(NAVY);
  doc.text(`${pct}%`, x + w + 3, by + 4);
}

/* ═══════════════════════════════════════ */
/*           MAIN EXPORT                  */
/* ═══════════════════════════════════════ */
export function generatePdfReport(results: ScanResults, meta: ReportMeta) {
  const doc = new jsPDF("p", "mm", "a4");

  const aiPct = results.ai ? Math.round(results.ai.score * 100) : 0;
  const humanPct = results.ai ? Math.round(results.ai.originalScore * 100) : 100;
  const plagPct = results.plagiarism ? Math.round(results.plagiarism.score) : 0;
  const accent = getAccent(aiPct);
  const verdict = getVerdict(aiPct);

  /* ── PAGE 1 ── */
  drawPageChrome(doc, accent);
  let y = 22;

  // Hero
  doc.setFillColor(NAVY);
  doc.roundedRect(MARGIN, y, CW, 30, 3, 3, "F");
  doc.setFontSize(16);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(WHITE);
  doc.text("Content Quality Report", MARGIN + 8, y + 12);
  // Badge
  const bw = doc.getTextWidth(verdict) + 10;
  doc.setFillColor(accent);
  doc.roundedRect(W - MARGIN - bw - 6, y + 5, bw, 10, 2, 2, "F");
  doc.setFontSize(8);
  doc.setTextColor(WHITE);
  doc.text(verdict, W - MARGIN - bw / 2 - 6, y + 12, { align: "center" });
  // Sub
  doc.setFontSize(7);
  doc.setFont("helvetica", "normal");
  doc.setTextColor("#B0BEC5");
  doc.text(`Words: ${meta.wordCount.toLocaleString()}  |  Date: ${formatDateBD(meta.scanDate)}  |  Audit: ${meta.auditId}`, MARGIN + 8, y + 22);
  y += 36;

  // Details
  doc.setFontSize(8);
  doc.setTextColor(GREY);
  const info = [
    `Document: ${meta.documentName || "Untitled Document"}`,
    meta.userEmail ? `User: ${meta.userEmail}` : null,
    `IP: ${meta.ipAddress || "N/A"}  |  Credits: ${meta.creditsUsed}`,
  ].filter(Boolean) as string[];
  info.forEach((l) => { doc.text(l, MARGIN, y); y += 5; });
  y += 4;

  // Score cards
  const cw = (CW - 6) / 2;
  const ch = 28;
  drawCard(doc, MARGIN, y, cw, ch, `${humanPct}%`, "Human Written", TEAL);
  drawCard(doc, MARGIN + cw + 6, y, cw, ch, `${aiPct}%`, "AI Detected", accent);
  y += ch + 4;
  drawCard(doc, MARGIN, y, cw, ch, `${plagPct}%`, "Plagiarism", plagPct > 20 ? RED : NAVY);
  drawCard(doc, MARGIN + cw + 6, y, cw, ch, getRiskLabel(aiPct), "Risk Level", accent);
  y += ch + 8;

  // Summary
  y = ensurePage(doc, y, 28, accent);
  doc.setFillColor(LIGHT);
  doc.roundedRect(MARGIN, y, CW, 24, 2, 2, "F");
  doc.setDrawColor("#DEE2E6");
  doc.roundedRect(MARGIN, y, CW, 24, 2, 2, "S");
  doc.setFontSize(8);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(NAVY);
  doc.text("Executive Summary", MARGIN + 5, y + 6);
  doc.setFontSize(7);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(GREY);
  const sum = `This ${meta.wordCount.toLocaleString()}-word document has been classified as "${verdict}" with ${humanPct}% human originality and ${aiPct}% AI-generated content. Plagiarism similarity: ${plagPct}%.`;
  doc.text(doc.splitTextToSize(sum, CW - 10), MARGIN + 5, y + 12);
  y += 30;

  // Bars
  y = ensurePage(doc, y, 50, accent);
  doc.setFontSize(9);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(NAVY);
  doc.text("Quality Signals Breakdown", MARGIN, y);
  y += 6;
  drawBar(doc, MARGIN, y, CW - 20, aiPct, "AI Pattern Level", accent);
  y += 14;
  drawBar(doc, MARGIN, y, CW - 20, humanPct, "Human Originality", TEAL);
  y += 14;
  if (results.plagiarism) {
    drawBar(doc, MARGIN, y, CW - 20, plagPct, "Plagiarism Match", plagPct > 20 ? RED : NAVY);
    y += 14;
  }

  /* ── SENTENCE TABLE ── */
  if (results.ai?.blocks && results.ai.blocks.length > 0) {
    y = newPage(doc, accent);
    doc.setFontSize(12);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(NAVY);
    doc.text("Sentence-by-Sentence AI Analysis", MARGIN, y);
    y += 8;

    const drawTableHeader = () => {
      doc.setFillColor(NAVY);
      doc.rect(MARGIN, y, CW, 8, "F");
      doc.setFontSize(6.5);
      doc.setFont("helvetica", "bold");
      doc.setTextColor(WHITE);
      doc.text("#", MARGIN + 3, y + 5.5);
      doc.text("Sentence Content", MARGIN + 12, y + 5.5);
      doc.text("Label", W - MARGIN - 32, y + 5.5);
      doc.text("Confidence", W - MARGIN - 16, y + 5.5);
      y += 8;
    };
    drawTableHeader();

    results.ai.blocks.forEach((block, i) => {
      const pct = Math.round(block.fake * 100);
      const label = getSentenceLabel(pct);
      const lc = getSentenceLabelColor(pct);
      const maxTW = CW - 55;
      const wrapped = doc.splitTextToSize(block.text, maxTW);
      const rh = Math.max(7, wrapped.length * 3.5 + 3);

      if (y + rh > 268) {
        y = newPage(doc, accent);
        drawTableHeader();
      }

      doc.setFillColor(i % 2 === 0 ? WHITE : LIGHT);
      doc.rect(MARGIN, y, CW, rh, "F");
      doc.setFontSize(6);
      doc.setFont("helvetica", "normal");
      doc.setTextColor(GREY);
      doc.text(String(i + 1), MARGIN + 3, y + 4.5);
      doc.setTextColor(NAVY);
      doc.text(wrapped, MARGIN + 12, y + 4.5);
      // Badge
      doc.setFillColor(lc);
      doc.roundedRect(W - MARGIN - 34, y + 1.5, 14, 5, 1, 1, "F");
      doc.setFontSize(5);
      doc.setFont("helvetica", "bold");
      doc.setTextColor(WHITE);
      doc.text(label, W - MARGIN - 27, y + 5, { align: "center" });
      // Bar
      const bx = W - MARGIN - 18;
      doc.setFillColor(LIGHT);
      doc.roundedRect(bx, y + 2, 12, 3, 0.5, 0.5, "F");
      doc.setFillColor(lc);
      doc.roundedRect(bx, y + 2, Math.max(12 * (pct / 100), 0.5), 3, 0.5, 0.5, "F");
      doc.setFontSize(5);
      doc.setTextColor(NAVY);
      doc.text(`${pct}%`, bx + 6, y + 8, { align: "center" });

      y += rh;
    });
  }

  /* ── SEAL (on last page) ── */
  y = ensurePage(doc, y, 65, accent);
  y += 12;
  const cx = W / 2;
  const cy = y + 22;

  // Outer
  doc.setDrawColor(accent);
  doc.setLineWidth(2.5);
  doc.circle(cx, cy, 22, "S");
  // Mid
  doc.setDrawColor(NAVY);
  doc.setLineWidth(1.5);
  doc.circle(cx, cy, 17, "S");
  // Inner
  doc.setDrawColor(accent);
  doc.setLineWidth(0.7);
  doc.circle(cx, cy, 13, "S");

  doc.setFontSize(8);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(accent);
  doc.text("THEOREX", cx, cy - 4, { align: "center" });
  doc.setFontSize(6);
  doc.setTextColor(NAVY);
  doc.text("CONSULTING", cx, cy + 1, { align: "center" });
  doc.setFontSize(5);
  doc.setTextColor(accent);
  doc.text("CERTIFIED AUDIT", cx, cy + 6, { align: "center" });
  doc.setFontSize(4);
  doc.text("AUTHENTICITY SEAL", cx, cy + 10, { align: "center" });

  y = cy + 30;
  // Signature
  doc.setDrawColor(NAVY);
  doc.setLineWidth(0.5);
  doc.line(cx - 35, y, cx + 35, y);
  y += 4;
  doc.setFontSize(6);
  doc.setTextColor(GREY);
  doc.text("Authorized Digital Signature — Theorex Consulting", cx, y, { align: "center" });

  // Save
  const ds = formatDateBD(meta.scanDate).replace(/\//g, "-");
  doc.save(`Theorex_Audit_Report_${ds}.pdf`);
}
