import jsPDF from "jspdf";
import type { ScanResults } from "@/types/scan";
import { formatDateBD } from "@/utils/dateFormat";

interface ReportMeta {
  auditId: string;
  scanDate: Date;
  ipAddress: string | null;
  wordCount: number;
  creditsUsed: number;
  documentName?: string;
  userEmail?: string;
}

const NAVY = "#1B263B";
const TEAL = "#00B894";
const RED = "#E53935";
const GREY = "#6B7280";
const LIGHT = "#F3F4F6";
const WHITE = "#FFFFFF";
const W = 210;
const MARGIN = 18;
const CW = W - MARGIN * 2;

function getAccentColor(aiPct: number) {
  return aiPct > 50 ? RED : TEAL;
}

function getVerdictLabel(aiPct: number) {
  return aiPct > 50 ? "AI Written" : "Human Written";
}

function getRiskLabel(pct: number) {
  if (pct <= 14) return "Clean";
  if (pct <= 39) return "Low Risk";
  if (pct <= 59) return "Moderate";
  if (pct <= 84) return "High Risk";
  return "Critical";
}

function getSentenceLabel(pct: number) {
  if (pct <= 30) return "Human";
  if (pct <= 60) return "Mixed";
  return "AI";
}

function getSentenceLabelColor(pct: number) {
  if (pct <= 30) return TEAL;
  if (pct <= 60) return "#FF9800";
  return RED;
}

/* ─── Page Header & Footer (disclaimers on every page) ─── */
function drawPageHeader(doc: jsPDF) {
  // Navy top bar
  doc.setFillColor(NAVY);
  doc.rect(0, 0, W, 10, "F");
  doc.setFillColor(TEAL);
  doc.rect(0, 10, W, 2, "F");

  // Header branding
  doc.setFontSize(7);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(WHITE);
  doc.text("Generated by Theorex Consulting", MARGIN, 7);
  doc.setFont("helvetica", "normal");
  doc.text("WhatsApp: +8801819185751", W - MARGIN, 7, { align: "right" });

  // Disclaimer line at top
  doc.setFontSize(5.5);
  doc.setTextColor(GREY);
  doc.text("Results are probabilistic estimates. Always apply human judgement.", W / 2, 16, { align: "center" });
}

function drawPageFooter(doc: jsPDF) {
  const footerY = 274;
  // Teal accent line
  doc.setFillColor(TEAL);
  doc.rect(0, footerY, W, 1.5, "F");

  doc.setFontSize(5);
  doc.setTextColor(GREY);
  doc.setFont("helvetica", "normal");
  const disclaimers = [
    "Results are probabilistic estimates. Always apply human judgement.",
    "Hybrid Text (AI + Human Generated) or Human Generated and Edited using any software, can also result in false positives.",
    "Partial context scans (e.g., testing only a portion of an article) may result in false positives; full context is necessary for accurate AI reporting.",
  ];
  let dy = footerY + 4;
  disclaimers.forEach((d) => {
    doc.text(d, W / 2, dy, { align: "center" });
    dy += 3;
  });

  // Bottom accent
  doc.setFillColor(NAVY);
  doc.rect(0, 293, W, 4, "F");
  doc.setFontSize(5);
  doc.setTextColor(WHITE);
  doc.text("Generated by Theorex Consulting — Promoting Transparency Over Mere Detection", W / 2, 296, { align: "center" });
}

function ensureNewPage(doc: jsPDF, y: number, needed: number): number {
  if (y + needed > 270) {
    doc.addPage();
    drawPageHeader(doc);
    drawPageFooter(doc);
    return 22;
  }
  return y;
}

/* ─── Score Card Helper ─── */
function drawScoreCard(doc: jsPDF, x: number, y: number, w: number, h: number, value: string, label: string, accent: string) {
  doc.setFillColor(LIGHT);
  doc.roundedRect(x, y, w, h, 2, 2, "F");
  doc.setDrawColor("#DEE2E6");
  doc.roundedRect(x, y, w, h, 2, 2, "S");

  doc.setFontSize(18);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(accent);
  doc.text(value, x + w / 2, y + h / 2 - 1, { align: "center" });

  doc.setFontSize(6.5);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(GREY);
  doc.text(label.toUpperCase(), x + w / 2, y + h / 2 + 7, { align: "center" });
}

/* ─── Horizontal bar helper ─── */
function drawHBar(doc: jsPDF, x: number, y: number, w: number, pct: number, label: string, color: string) {
  doc.setFontSize(7);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(NAVY);
  doc.text(label, x, y);

  const barY = y + 2;
  const barH = 5;
  // Background
  doc.setFillColor(LIGHT);
  doc.roundedRect(x, barY, w, barH, 1, 1, "F");
  // Filled
  const filled = Math.max(w * (pct / 100), 1);
  doc.setFillColor(color);
  doc.roundedRect(x, barY, filled, barH, 1, 1, "F");

  doc.setFontSize(7);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(NAVY);
  doc.text(`${pct}%`, x + w + 3, barY + 4);
}

export function generatePdfReport(results: ScanResults, meta: ReportMeta) {
  const doc = new jsPDF("p", "mm", "a4");

  const aiPct = results.ai ? Math.round(results.ai.score * 100) : 0;
  const humanPct = results.ai ? Math.round(results.ai.originalScore * 100) : 100;
  const plagPct = results.plagiarism ? Math.round(results.plagiarism.score) : 0;
  const accent = getAccentColor(aiPct);
  const verdict = getVerdictLabel(aiPct);

  // ══════════════════════════════════════
  // PAGE 1: Content Quality Report
  // ══════════════════════════════════════
  drawPageHeader(doc);
  drawPageFooter(doc);

  let y = 22;

  // Hero banner
  doc.setFillColor(NAVY);
  doc.roundedRect(MARGIN, y, CW, 30, 3, 3, "F");

  doc.setFontSize(16);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(WHITE);
  doc.text("Content Quality Report", MARGIN + 8, y + 12);

  // Verdict badge
  const badgeW = doc.getTextWidth(verdict) + 10;
  doc.setFillColor(accent);
  doc.roundedRect(W - MARGIN - badgeW - 6, y + 5, badgeW, 10, 2, 2, "F");
  doc.setFontSize(8);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(WHITE);
  doc.text(verdict, W - MARGIN - badgeW / 2 - 6, y + 12, { align: "center" });

  // Sub-info line
  doc.setFontSize(7);
  doc.setFont("helvetica", "normal");
  doc.setTextColor("#B0BEC5");
  doc.text(`Words: ${meta.wordCount.toLocaleString()}  |  Date: ${formatDateBD(meta.scanDate)}  |  Audit: ${meta.auditId}`, MARGIN + 8, y + 22);

  y += 36;

  // Document details
  doc.setFontSize(8);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(GREY);
  const detailLines = [
    `Document: ${meta.documentName || "Untitled Document"}`,
    meta.userEmail ? `User: ${meta.userEmail}` : null,
    `IP: ${meta.ipAddress || "N/A"}  |  Credits: ${meta.creditsUsed}`,
  ].filter(Boolean) as string[];
  detailLines.forEach((line) => {
    doc.text(line, MARGIN, y);
    y += 5;
  });

  y += 4;

  // Score cards (2x2 grid)
  const cardW = (CW - 6) / 2;
  const cardH = 28;
  drawScoreCard(doc, MARGIN, y, cardW, cardH, `${humanPct}%`, "Human Written", TEAL);
  drawScoreCard(doc, MARGIN + cardW + 6, y, cardW, cardH, `${aiPct}%`, "AI Detected", aiPct > 50 ? RED : NAVY);
  y += cardH + 4;
  drawScoreCard(doc, MARGIN, y, cardW, cardH, `${plagPct}%`, "Plagiarism", plagPct > 20 ? RED : NAVY);
  drawScoreCard(doc, MARGIN + cardW + 6, y, cardW, cardH, getRiskLabel(aiPct), "Risk Level", accent);
  y += cardH + 8;

  // Executive Summary
  y = ensureNewPage(doc, y, 30);
  doc.setFillColor(LIGHT);
  doc.roundedRect(MARGIN, y, CW, 24, 2, 2, "F");
  doc.setDrawColor("#DEE2E6");
  doc.roundedRect(MARGIN, y, CW, 24, 2, 2, "S");

  doc.setFontSize(8);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(NAVY);
  doc.text("Executive Summary", MARGIN + 5, y + 6);

  doc.setFontSize(7);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(GREY);
  const summaryText = `This ${meta.wordCount.toLocaleString()}-word document has been analyzed and classified as "${verdict}" with ${humanPct}% human originality and ${aiPct}% AI-generated content detected. Plagiarism similarity is at ${plagPct}%.`;
  const summaryLines = doc.splitTextToSize(summaryText, CW - 10);
  doc.text(summaryLines, MARGIN + 5, y + 12);
  y += 30;

  // Quality Signals Breakdown
  y = ensureNewPage(doc, y, 30);
  doc.setFontSize(9);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(NAVY);
  doc.text("Quality Signals Breakdown", MARGIN, y);
  y += 6;

  drawHBar(doc, MARGIN, y, CW - 20, aiPct, "AI Pattern Level", aiPct > 50 ? RED : "#FF9800");
  y += 14;
  drawHBar(doc, MARGIN, y, CW - 20, humanPct, "Human Originality", TEAL);
  y += 14;
  if (results.plagiarism) {
    drawHBar(doc, MARGIN, y, CW - 20, plagPct, "Plagiarism Match", plagPct > 20 ? RED : NAVY);
    y += 14;
  }

  // ══════════════════════════════════════
  // PAGE 2+: Sentence-by-Sentence Analysis
  // ══════════════════════════════════════
  if (results.ai?.blocks && results.ai.blocks.length > 0) {
    doc.addPage();
    drawPageHeader(doc);
    drawPageFooter(doc);
    y = 22;

    doc.setFontSize(12);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(NAVY);
    doc.text("Sentence-by-Sentence AI Analysis", MARGIN, y);
    y += 8;

    // Table header
    doc.setFillColor(NAVY);
    doc.rect(MARGIN, y, CW, 8, "F");
    doc.setFontSize(6.5);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(WHITE);
    doc.text("#", MARGIN + 3, y + 5.5);
    doc.text("Sentence Content", MARGIN + 12, y + 5.5);
    doc.text("Label", W - MARGIN - 32, y + 5.5);
    doc.text("Confidence", W - MARGIN - 16, y + 5.5);
    y += 8;

    results.ai.blocks.forEach((block, i) => {
      const pct = Math.round(block.fake * 100);
      const label = getSentenceLabel(pct);
      const labelColor = getSentenceLabelColor(pct);

      // Estimate row height
      const maxTextW = CW - 55;
      const wrappedLines = doc.splitTextToSize(block.text, maxTextW);
      const rowH = Math.max(7, wrappedLines.length * 3.5 + 3);

      if (y + rowH > 268) {
        doc.addPage();
        drawPageHeader(doc);
        drawPageFooter(doc);
        y = 22;

        // Re-draw table header
        doc.setFillColor(NAVY);
        doc.rect(MARGIN, y, CW, 8, "F");
        doc.setFontSize(6.5);
        doc.setFont("helvetica", "bold");
        doc.setTextColor(WHITE);
        doc.text("#", MARGIN + 3, y + 5.5);
        doc.text("Sentence Content", MARGIN + 12, y + 5.5);
        doc.text("Label", W - MARGIN - 32, y + 5.5);
        doc.text("Confidence", W - MARGIN - 16, y + 5.5);
        y += 8;
      }

      const rowBg = i % 2 === 0 ? WHITE : LIGHT;
      doc.setFillColor(rowBg);
      doc.rect(MARGIN, y, CW, rowH, "F");

      doc.setFontSize(6);
      doc.setFont("helvetica", "normal");
      doc.setTextColor(GREY);
      doc.text(String(i + 1), MARGIN + 3, y + 4.5);

      doc.setTextColor(NAVY);
      doc.text(wrappedLines, MARGIN + 12, y + 4.5);

      // Label badge
      doc.setFillColor(labelColor);
      doc.roundedRect(W - MARGIN - 34, y + 1.5, 14, 5, 1, 1, "F");
      doc.setFontSize(5);
      doc.setFont("helvetica", "bold");
      doc.setTextColor(WHITE);
      doc.text(label, W - MARGIN - 27, y + 5, { align: "center" });

      // Confidence bar
      const barX = W - MARGIN - 18;
      const barW = 12;
      doc.setFillColor(LIGHT);
      doc.roundedRect(barX, y + 2, barW, 3, 0.5, 0.5, "F");
      doc.setFillColor(labelColor);
      doc.roundedRect(barX, y + 2, Math.max(barW * (pct / 100), 0.5), 3, 0.5, 0.5, "F");
      doc.setFontSize(5);
      doc.setTextColor(NAVY);
      doc.text(`${pct}%`, barX + barW / 2, y + 8, { align: "center" });

      y += rowH;
    });
  }

  // ══════════════════════════════════════
  // LAST PAGE: Professional Seal & Footer
  // ══════════════════════════════════════
  y = ensureNewPage(doc, y, 60);
  y += 10;

  // Seal
  const sealCx = W / 2;
  const sealCy = y + 18;

  // Outer ring
  doc.setDrawColor(TEAL);
  doc.setLineWidth(2);
  doc.circle(sealCx, sealCy, 18, "S");
  // Inner ring
  doc.setDrawColor(NAVY);
  doc.setLineWidth(1.2);
  doc.circle(sealCx, sealCy, 14, "S");
  // Inner accent
  doc.setDrawColor(TEAL);
  doc.setLineWidth(0.5);
  doc.circle(sealCx, sealCy, 11, "S");

  doc.setFontSize(7);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(NAVY);
  doc.text("THEOREX", sealCx, sealCy - 3, { align: "center" });
  doc.setFontSize(5);
  doc.text("CONSULTING", sealCx, sealCy + 1, { align: "center" });
  doc.setFontSize(4);
  doc.setTextColor(TEAL);
  doc.text("VERIFIED", sealCx, sealCy + 5, { align: "center" });
  doc.setFontSize(3.5);
  doc.text("AUTHENTICITY SEAL", sealCx, sealCy + 8, { align: "center" });

  y = sealCy + 24;

  // Signature line
  doc.setDrawColor(NAVY);
  doc.setLineWidth(0.5);
  doc.line(sealCx - 35, y, sealCx + 35, y);
  y += 4;
  doc.setFontSize(6);
  doc.setTextColor(GREY);
  doc.text("Authorized Digital Signature — Theorex Consulting", sealCx, y, { align: "center" });

  // Download
  const dateStr = formatDateBD(meta.scanDate).replace(/\//g, "-");
  doc.save(`Theorex_Audit_Report_${dateStr}.pdf`);
}
